### ISSUE TITLE
Having trouble running the npm scripts

### ISSUE THREAD

**Issue by kristianmandrup** [JonJam/fake-rest-api#1]
```
fake-rest-api git:(master) ✗ npm run generate-mock-api-data

> fake-rest-api@1.0.0 generate-mock-api-data /Users/kristianmandrup/repos/yeay/fake-rest-api
> ts-node buildScripts/generateData.ts


/Users/kristianmandrup/repos/yeay/fake-rest-api/node_modules/json-schema-faker/lib/index.js:1039
            throw new Error(e.message + ' in ' + '/' + e.path.join('/'));
                  ^
Error: cannot resolve faker-generator for "random.uuid" in /properties/groups/items/0/properties/id
    at run (/Users/kristianmandrup/repos/yeay/fake-rest-api/node_modules/json-schema-faker/lib/index.js:1039:19)
    at jsf (/Users/kristianmandrup/repos/yeay/fake-rest-api/node_modules/json-schema-faker/lib/index.js:1048:12)
    at Object.<anonymous> (/Users/kristianmandrup/repos/yeay/fake-rest-api/buildScripts/generateData.ts:10:29)
```

Please advice. Thanks :)

**Comment by kristianmandrup** [comment]
Turns out the error is thrown from `json-schema-faker`, error message defined in `string.json`

```js
      {
        "description": "should validate custom formats",
        "schema": {
          "type": "object",
          "properties": {
            "test": {
              "type": "string",
              "faker": "not.exists"
            }
          },
          "required": ["test"]
        },
        "throws": "cannot resolve faker-generator for .+? in \\/properties\\/test"
      },
```

**Comment by kristianmandrup** [comment]
So it seems to originate from here, ie. the `faker: "random.uuid"`

```js
var groupSchema = {
    type: "object",
    properties: {
        groups: {
            type: "array",
            minItems: 0,
            maxItems: 5,
            uniqueItems: true,
            items: {
                type: "object",
                properties: {
                    id: {
                        type: "string",
                        faker: "random.uuid"
                    },
```

**Comment by kristianmandrup** [comment]
From `v0.5.x` and beyond we'll not longer bundle external generators, locales and such due the unnecessary waste of time and space.

Since `v0.5.x` external generators are not longer bundled with jsf, however built-in defaults are shipped for all basic types and formats.

So I guess we have to include `random` and `commerce` etc. explicitly now

**Comment by kristianmandrup** [comment]
However, `random.uuid` is part of [faker core API](https://marak.github.io/faker.js/#toc9__anchor) so kinda strange why it fails!

**Comment by kristianmandrup** [comment]
But your repo depends on `0.4.x` 

`"json-schema-faker": "^0.4.3",`

So why does it not work!?

**Comment by kristianmandrup** [comment]
So I would think for some reason, we now need to extend with faker explicitly...???

`jsf` has built-in generators for core-formats, [Faker.js](https://github.com/marak/Faker.js/) and [Chance.js](http://chancejs.com/) (and others) are also supported but they require setup:

```js
jsf.extend('faker', function() {
  return require('faker');
});
```

```json
{
  "type": "string",
  "faker": "internet.email"
}
```

**Comment by kristianmandrup** [comment]
Finally managed to fix it using above recipe. Also added much better install and usage instructions etc

https://github.com/yeay-tv/fake-rest-api

**Comment by JonJam** [comment]
Hi @kristianmandrup thank you for raising this.

I think the issue is that I use yarn not npm, so its installing the latest version rather than the one I built against.

I will update the README to add more specific instructions.

**Comment by Webbrother** [comment]
I also have the same issue.
I found that it works fine if replace 
```
import { green, red } from "chalk";
```
with 
```
import chalk from "chalk";
const { green, red } = chalk;
```
in `fake-rest-api/buildScripts/generateData.ts`.

Any ideas of such behavior?

**Comment by JonJam** [comment]
@Webbrother I think the issue is that I use yarn not npm, so its installing the latest version rather than the one I built against.

**Comment by Webbrother** [comment]
@JonJam , but I use `npm`, not `yarn`.
